#server.servlet.context-path: /api

spring:
  datasource:
    url: jdbc:h2:file:~/pedmonitor/data
    driverClassName: org.h2.Driver
    username: ${DB_USER:dbuser}
    password: ${DB_PASSWORD:dbpassword}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
      globally_quoted_identifiers: true

  h2:
    console:
      enabled: true

  flyway:
    enabled: true
    url: jdbc:h2:file:~/pedmonitor/data
    baseline-on-migrate: true
    user: ${DB_USER:dbuser}
    password: ${DB_PASSWORD:dbpassword}

# APP Process specific properties
app:
  indicators:
    FET0:
      unit: kWh/a
      title: "Total district final energy consumption"
      categoryLabel: Energy
      kpi: true
      overallKPIS: "PET0"
      greenHouseGasEmissionKPI: "FET0_GHG_"
      parent: "NONE"
    FET1:
      unit: kWh/a
      title: "Total final energy consumption: buildings, equipment/facilities and industries"
      categoryLabel: Energy
      kpi: true
      overallKPIS: "PET1"
      greenHouseGasEmissionKPI: "FET1_GHG_"
      parent: "FET0"
    FET2:
      unit: kWh/a
      title: "Total final energy consumption: transport"
      categoryLabel: Energy
      kpi: true
      overallKPIS: "PET2"
      greenHouseGasEmissionKPI: "FET2_GHG_"
      parent: "FET0"
    FET3:
      unit: kWh/a
      title: "Total final energy consumption: other sectors"
      categoryLabel: Energy
      overallKPIS: "PET3"
      greenHouseGasEmissionKPI: "FET3_GHG_"
      kpi: true
      parent: "FET0"
    FET1_1:
      unit: kWh/a
      title: "Subtotal Municipal Final energy consumption"
      categoryLabel: Energy
      kpi: true
      greenHouseGasEmissionKPI: "FET1_1_GHG_"
      parent: "FET1"
    FET1_1_1:
      unit: kWh/a
      title: "Energy consumption: municipal buildings, equipment/facilities"
      categoryLabel: Energy
      parent: "FET1_1"
    FET1_1_2:
      unit: kWh/a
      title: "Energy consumption: public lighting"
      categoryLabel: Energy
      parent: "FET1_1"
    FET1_1_3:
      unit: kWh/a
      title: "Energy consumption: other municipal category"
      categoryLabel: Energy
      parent: "FET1_1"
    FET1_2:
      unit: kWh/a
      title: "Subtotal Tertiary (non-Municipal) Final energy consumption"
      categoryLabel: Energy
      kpi: true
      greenHouseGasEmissionKPI: "FET1_2_GHG_"
      parent: "FET1"
    FET1_2_1:
      unit: kWh/a
      title: "Energy consumption: institutional buildings, non-municipal"
      categoryLabel: Energy
      parent: "FET1_2"
    FET1_2_2:
      unit: kWh/a
      title: "Energy consumption: other non-municipal category"
      categoryLabel: Energy
      parent: "FET1_2"
    FET1_3:
      unit: kWh/a
      title: "Energy consumption: residential buildings"
      categoryLabel: Energy
      kpi: true
      greenHouseGasEmissionKPI: "FET1_3_GHG_"
      parent: "FET1"
    FET1_4:
      unit: kWh/a
      title: "Subtotal Industry Final energy consumption"
      categoryLabel: Energy
      kpi: true
      greenHouseGasEmissionKPI: "FET1_4_GHG_"
      parent: "FET1"
    FET1_4_1:
      unit: kWh/a
      title: "Energy consumption: non-ETS industry"
      categoryLabel: Energy
      parent: "FET1_4"
    FET1_4_2:
      unit: kWh/a
      title: "Energy consumption: ETS"
      categoryLabel: Energy
      parent: "FET1_4"
    FET2_1:
      unit: kWh/a
      title: "Subtotal Municipal Fleet energy consumption"
      categoryLabel: Energy
      kpi: true
      greenHouseGasEmissionKPI: "FET2_1_GHG_"
      parent: "FET2"
    FET2_1_1:
      unit: kWh/a
      title: "Energy consumption: road fleet"
      categoryLabel: Energy
      parent: "FET2_1"
    FET2_1_2:
      unit: kWh/a
      title: "Energy consumption: other fleet"
      categoryLabel: Energy
      parent: "FET2_1"
    FET2_2:
      unit: kWh/a
      title: "Subtotal Public transport energy consumption"
      categoryLabel: Energy
      kpi: true
      greenHouseGasEmissionKPI: "FET2_2_GHG_"
      parent: "FET2"
    FET2_2_1:
      unit: kWh/a
      title: "Energy consumption: public road transport"
      categoryLabel: Energy
      parent: "FET2_2"
    FET2_2_2:
      unit: kWh/a
      title: "Energy consumption: public rail"
      categoryLabel: Energy
      parent: "FET2_2"
    FET2_2_3:
      unit: kWh/a
      title: "Energy consumption: public local and domestic waterways"
      categoryLabel: Energy
      parent: "FET2_2"
    FET2_2_4:
      unit: kWh/a
      title: "Energy consumption: other public transport categories"
      categoryLabel: Energy
      parent: "FET2_2"
    FET2_3:
      unit: kWh/a
      title: "Subtotal Private and commercial transport energy consumption"
      categoryLabel: Energy
      kpi: true
      greenHouseGasEmissionKPI: "FET2_3_GHG_"
      parent: "FET2"
    FET2_3_1:
      unit: kWh/a
      title: "Energy consumption: private road transport"
      categoryLabel: Energy
      parent: "FET2_3"
    FET2_3_2:
      unit: kWh/a
      title: "Energy consumption: private rail"
      categoryLabel: Energy
      parent: "FET2_3"
    FET2_3_3:
      unit: kWh/a
      title: "Energy consumption: private local and domestic waterways"
      categoryLabel: Energy
      parent: "FET2_3"
    FET2_3_4:
      unit: kWh/a
      title: "Energy consumption: private local aviation"
      categoryLabel: Energy
      parent: "FET2_3"
    FET2_3_5:
      unit: kWh/a
      title: "Energy consumption: other private transport categories"
      categoryLabel: Energy
      parent: "FET2_3"
    FET2_4:
      unit: kWh/a
      title: "Energy consumption: Other type of transport"
      categoryLabel: Energy
      kpi: true
      greenHouseGasEmissionKPI: "FET2_4_GHG_"
      parent: "FET2"
    FET3_1:
      unit: kWh/a
      title: "Subtotal other sectors energy consumption"
      categoryLabel: Energy
      kpi: true
      greenHouseGasEmissionKPI: "FET3_1_GHG_"
      parent: "FET3"
    FET3_1_1:
      unit: kWh/a
      title: "Agriculture, Forestry, Fisheries"
      categoryLabel: Energy
      parent: "FET3_1"
    FET3_1_2:
      unit: kWh/a
      title: "Other not allocated"
      categoryLabel: Energy
      parent: "FET3_1"

    PET0:
      unit: kWh/a
      title: "Total district primary energy consumption"
      categoryLabel: Energy
      kpi: true
      parent: "NONE"
    PET1:
      unit: kWh/a
      title: "Total primary energy consumption: buildings, equipment/facilities and industries"
      categoryLabel: Energy
      kpi: true
      parent: "NONE"
    PET2:
      unit: kWh/a
      title: "Total primary energy consumption: transport"
      categoryLabel: Energy
      kpi: true
      parent: "NONE"
    PET3:
      unit: kWh/a
      title: "Total primary energy consumption: other sectors"
      categoryLabel: Energy
      kpi: true
      parent: "NONE"

    RES0:
      unit: kWh/a
      title: "RES generation"
      categoryLabel: Energy
      kpi: true
      parent: "NONE"
    RESX:
      unit: kWh/a
      title: "Local electricity production"
      categoryLabel: Energy
      parent: "RES0"

    SS:
      unit: "%"
      title: "Degree of energetic self-supply by RES"
      categoryLabel: Energy
      kpi: true
      parent: "NONE"

    OVERALL_RES:
      unit: "%"
      title: "PED / PEN achievement rate for renewable energy"
      categoryLabel: OVERALL_RES
      parent: "NONE"
    OVERALL_GHG:
      unit: "%"
      title: "PED / PEN achievement rate for GHg emissions"
      categoryLabel: OVERALL_GHG
      kpi: true
      parent: "NONE"
    OVERALL_GHG_RES:
      unit: "%"
      title: "PED / PEN achievement rate "
      categoryLabel: OVERALL_GHG_RES
      kpi: true
      parent: "NONE"